# Generated by Django 3.2.19 on 2023-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowoof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=2000)),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '建议',
                'verbose_name_plural': '建议',
                'ordering': ['-views'],
            },
        ),
        migrations.AlterField(
            model_name='pet',
            name='info',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tool',
            name='info',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
