# Generated by Django 3.2.19 on 2023-05-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowoof', '0002_auto_20230527_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='picture',
            field=models.ImageField(default='default_tool_picture.jpg', upload_to='tool_picture/'),
        ),
    ]
